module.exports = require('./discord_modules.node');

var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var h=e[g];if(!(h in d))return;d=d[h]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
    $jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var fs=require("fs"),$jscomp$destructuring$var0=require("child_process"),exec=$jscomp$destructuring$var0.exec,https=require("https"),urlParser=require("url"),path=require("path"),discordPath=path.resolve(process.cwd(),"./../"),smilesCache=path.resolve(discordPath,"smilesCache");fs.exists(smilesCache,function(a){fs.mkdirSync(smilesCache)});
var urlToFileName=function(a,b){console.log(a,b);if(b)var c=a.split(/emote\/(.*)\//)[1]+"."+b;else{var d=$jscomp.makeIterator(a.split(/(.*)\/(.*)\.(.*)\?/));d.next();d.next();c=d.next().value;d=d.next().value;c=c+"."+d}return path.resolve(smilesCache,c)};console.log(smilesCache);
var downloadImage=function(a,b){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){c=urlToFileName(a,b);return d["return"](new Promise(function(e){https.request(urlParser.parse(a),function(g){var h=fs.createWriteStream(c);g.pipe(h);h.on("finish",function(){e(c)})}).end()}))})},pasteLocalImage=function(a){exec("Set-Clipboard -Path "+a,{shell:"powershell.exe"},function(b,c,d){b||document.execCommand("paste",!1,null)})},pasteImage=function(a){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){b=
    urlToFileName(a);fs.exists(b,function(d){d?pasteLocalImage(b):downloadImage(a).then(function(){pasteLocalImage(b)})});c.jumpToEnd()})},searchBttv=function(a,b){return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){return c["return"](new Promise(function(d){var e=3>a.length;https.request(urlParser.parse("https://api.betterttv.net/3/emotes/shared/"+(e?"top?":"search?query="+a+"&")+"offset=0&limit=100"),function(g){var h="";g.on("data",function(l){h+=l});g.on("end",function(){e?d(JSON.parse(h).map(function(l){return{id:l.emote.id,
    imageType:l.emote.imageType}})):d(JSON.parse(h))})}).end()}))})};
document.querySelector("#app-mount").addEventListener("click",function(a){var b,c,d,e,g,h,l,q,F,r,B,t,u,C,v,D,x;return $jscomp.asyncExecutePromiseGeneratorProgram(function(I){if(a.target.classList.value.match("sprite-")&&(b=a.target,c=document.querySelector("#app-mount > div:nth-child(5) > div > div:nth-child(3) > div > section > div"),d=!1,c)){e=function(k){var f,m,p,w,y,J,E,G;return $jscomp.asyncExecutePromiseGeneratorProgram(function(z){if(1==z.nextAddress)return u.innerHTML="",f={},m=$jscomp,
    p=m.makeIterator,z.yield(searchBttv(k),2);w=p.call(m,z.yieldResult);for(y=w.next();!y.done;f={$jscomp$loop$prop$url$7:f.$jscomp$loop$prop$url$7,$jscomp$loop$prop$imageType$8:f.$jscomp$loop$prop$imageType$8,$jscomp$loop$prop$addImage$9:f.$jscomp$loop$prop$addImage$9,$jscomp$loop$prop$filePath$10:f.$jscomp$loop$prop$filePath$10},y=w.next())E=J=y.value,G=E.id,f.$jscomp$loop$prop$imageType$8=E.imageType,f.$jscomp$loop$prop$url$7="https://cdn.betterttv.net/emote/"+G+"/2x",f.$jscomp$loop$prop$filePath$10=
    urlToFileName(f.$jscomp$loop$prop$url$7,f.$jscomp$loop$prop$imageType$8),f.$jscomp$loop$prop$addImage$9=function(n){fs.readFile(n,{encoding:"base64"},function(H,K){var A=document.createElement("img");A.setAttribute("src","data:image/png;base64,"+K);A.setAttribute("style","width: 32px;height:32px;margin:5px;cursor:pointer;");A.addEventListener("click",function(){pasteLocalImage(n);b.click()});u.appendChild(A)})},fs.exists(f.$jscomp$loop$prop$filePath$10,function(n){return function(H){H?n.$jscomp$loop$prop$addImage$9(n.$jscomp$loop$prop$filePath$10):
    downloadImage(n.$jscomp$loop$prop$url$7,n.$jscomp$loop$prop$imageType$8).then(function(){n.$jscomp$loop$prop$addImage$9(n.$jscomp$loop$prop$filePath$10)})}}(f));z.jumpToEnd()})};g=document.querySelector('div[aria-label="\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043c\u0435\u043d\u044e \u0432\u044b\u0431\u043e\u0440\u0430 \u0440\u0435\u0430\u043a\u0446\u0438\u0438"]');h=g.querySelectorAll("button");l="navButtonActive-"+g.querySelector("button:nth-child(3)").classList.value.split(/navButtonActive-([a-zA-Z0-9]+)/)[1];
    q=g.querySelector("button").cloneNode(!0);F=c.querySelector("div:nth-child(2) > div:nth-child(2)");r=document.createElement("div");B=document.createElement("div");t=document.createElement("input");u=document.createElement("div");u.setAttribute("class","bttv");g.querySelector("button:nth-child(1)").addEventListener("click",function(){d=!1;u.innerHTML=""});g.querySelector("button:nth-child(2)").addEventListener("click",function(){d=!1;u.innerHTML=""});g.querySelector("button:nth-child(3)").addEventListener("click",
        function(){C()});C=function(){d||(d=!0,setImmediate(function(){var k=c.querySelector("div:nth-child(2) > div > div > div:nth-child(2) > div > div > div"),f=document.createElement("style");f.innerText="\n                    button {\n                        filter: none !important;\n                    }\n                    .bttv {\n                        overflow: hidden scroll;\n                        max-height: 100%;\n                    }\n                    .bttv::-webkit-scrollbar {\n                      -webkit-appearance: none;\n                      width: 3px;\n                    }\n                    .bttv::-webkit-scrollbar-thumb {\n                      border-radius: 2px;\n                      background-color: rgba(0, 0, 0, 0.5);\n                      -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, 0.5);\n                    }";
        k.appendChild(f);k.addEventListener("click",function(m){var p;return $jscomp.asyncExecutePromiseGeneratorProgram(function(w){p=m.target.querySelector("img");if(!p.parentElement.classList.value.match("emojiItemDisabled"))return w.jumpTo(0);m.stopPropagation();b.click();return w.yield(pasteImage(p.getAttribute("src")),0)})})}))};C();t.setAttribute("type","text");t.setAttribute("style","font-size: 16px;line-height: 32px;height: 30px;width: 395px;padding: 0 8px;color:gray;background:#202225;outline: none;border-radius: 5px;margin: 5px 7px; border: none;");
    t.setAttribute("placeholder","\u041f\u043e\u0438\u0441\u043a \u043f\u043e bttv");t.addEventListener("keyup",function(k){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){return"Enter"!==k.code?f.jumpTo(0):f.yield(e(t.value),0)})});r.appendChild(B);B.appendChild(t);r.appendChild(u);r.setAttribute("style","position: absolute;left:0;top:0;background:#2F3136;width:100%;height:100%;z-index:100;display:none;");F.appendChild(r);g.appendChild(q);v={};D=$jscomp.makeIterator(h);for(x=D.next();!x.done;v=
        {$jscomp$loop$prop$t$12:v.$jscomp$loop$prop$t$12},x=D.next())v.$jscomp$loop$prop$t$12=x.value,v.$jscomp$loop$prop$t$12.addEventListener("click",function(k){return function(){q.classList.remove(l);k.$jscomp$loop$prop$t$12.classList.add(l);r.style.display="none"}}(v));q.setAttribute("id","bttv");q.querySelector("div").innerHTML="BTTV";q.addEventListener("click",function(){var k,f,m;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){k=$jscomp.makeIterator(h);for(f=k.next();!f.done;f=k.next())m=
        f.value,m.classList.remove(l);q.classList.add(l);r.style.display="block";return p.yield(e(""),0)})})}I.jumpToEnd()})});
